<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sektor.TurnBased.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sektor.TurnBased.Core.Abstractions\Sektor.TurnBased.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
