<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Sektor.TurnBased.UI.Core.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UI\Sektor.TurnBased.UI.Core\Sektor.TurnBased.UI.Core.csproj" />
    <ProjectReference Include="..\..\src\UI\Sektor.TurnBased.UI.ViewModels\Sektor.TurnBased.UI.ViewModels.csproj" />
  </ItemGroup>

</Project>
