<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sektor.Network.Steam</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sektor.Network.Abstractions\Sektor.Network.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\Sektor.TurnBased.Core.Abstractions\Sektor.TurnBased.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
